# Generated by Django 4.0.4 on 2022-12-10 19:45

from django.db import migrations, models
import finding_people.models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhardata',
            name='serial',
            field=models.IntegerField(default=finding_people.models.Serial_Generator('Aadhar Data'), unique=True),
        ),
        migrations.AddField(
            model_name='firdata',
            name='serial',
            field=models.IntegerField(default=finding_people.models.Serial_Generator('FIR Data'), unique=True),
        ),
    ]
