# Generated by Django 4.0.4 on 2022-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0004_alter_trainigimagesdata_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinguserdata',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
