# Generated by Django 4.0.4 on 2022-12-11 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0006_remove_trackinguserdata_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinguserdata',
            name='date_at_droped',
            field=models.DateField(default=datetime.date(2022, 12, 12)),
        ),
        migrations.AddField(
            model_name='trackinguserdata',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='trackinguserdata',
            name='police_station_droped',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(0, 15, 59, 471287)),
        ),
    ]
