# Generated by Django 4.0.4 on 2022-12-11 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0007_trackinguserdata_date_at_droped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinguserdata',
            name='uid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(0, 23, 18, 626753)),
        ),
    ]
