# Generated by Django 4.0.4 on 2022-12-15 09:02

import datetime
from django.db import migrations, models
import django.utils.timezone
import finding_people.models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0009_alluserstrackingdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_user_id_proof',
            field=models.ImageField(blank=True, upload_to=finding_people.models.PathAndRename('User Verfication ID Proof')),
        ),
        migrations.AlterField(
            model_name='aadhardata',
            name='VID',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='aadhardata',
            name='card_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='alluserstrackingdata',
            name='uid',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='firdata',
            name='fir_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='firdata',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='date_at_droped',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(14, 32, 52, 882330)),
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='uid',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='traineddataset',
            name='aadhar_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='traineddataset',
            name='serial',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trainigimagesdata',
            name='serial',
            field=models.BigIntegerField(),
        ),
    ]
