# Generated by Django 4.0.4 on 2022-12-19 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0010_user_aadhar_number_user_aadhar_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(19, 47, 19, 357369)),
        ),
    ]
