# Generated by Django 4.0.4 on 2022-12-20 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0011_alter_trackinguserdata_time_at_droped'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationid', models.BigIntegerField(null=True, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='TrainigImagesData',
            new_name='ExtractFacesData',
        ),
        migrations.DeleteModel(
            name='AllUsersTrackingData',
        ),
        migrations.RenameField(
            model_name='trackinguserdata',
            old_name='uid',
            new_name='case_id',
        ),
        migrations.RenameField(
            model_name='trackinguserdata',
            old_name='name',
            new_name='case_name',
        ),
        migrations.RenameField(
            model_name='trackinguserdata',
            old_name='profile',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(12, 26, 41, 988468)),
        ),
    ]
