# Generated by Django 4.0.4 on 2022-12-20 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0014_rename_police_station_droped_trackinguserdata_police_station_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestationdata',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(13, 10, 2, 152362)),
        ),
    ]
