# Generated by Django 4.0.4 on 2022-12-20 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0015_policestationdata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(13, 11, 10, 87739)),
        ),
    ]
