# Generated by Django 4.0.4 on 2022-12-20 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0017_alter_trackinguserdata_time_at_droped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(16, 32, 51, 454158)),
        ),
    ]
