# Generated by Django 4.0.4 on 2023-03-08 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0018_alter_trackinguserdata_time_at_droped'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.BigIntegerField(null=True, unique=True)),
                ('aadhar_number', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='aadhardata',
            name='mobile',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(10, 1, 20, 77958)),
        ),
    ]
