# Generated by Django 4.0.4 on 2023-03-08 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0019_userdetails_aadhardata_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(10, 5, 29, 947820)),
        ),
    ]
