# Generated by Django 4.1.7 on 2023-03-13 12:17

import datetime
from django.db import migrations, models
import finding_people.models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0020_alter_trackinguserdata_time_at_droped'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_verifed_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='kyc_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=finding_people.models.PathAndRename('User Profile Images')),
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(17, 47, 23, 577085)),
        ),
    ]
