# Generated by Django 4.1.7 on 2023-03-14 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finding_people', '0021_userdetails_is_verifed_user_userdetails_kyc_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='is_verifed_user',
            new_name='is_verified_user',
        ),
        migrations.AlterField(
            model_name='trackinguserdata',
            name='time_at_droped',
            field=models.TimeField(default=datetime.time(11, 59, 9, 337488)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='DOB',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='aadhar_number',
            field=models.BigIntegerField(default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
